Lint and comments

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -23,7 +23,7 @@ jobs:
                 cat REASON | sed 's/.$/\n/'
                 echo 'EOF'
               } >> "$GITHUB_OUTPUT"
-              exit 1
+              exit 1 # Make the job fail for visibility https://github.com/pixiebrix/pixiebrix-extension/pull/7700#issuecomment-1969527384
             fi
           }
       - name: Hide previous comment if resolved
@@ -149,6 +149,6 @@ jobs:
           ALL_CHANGED_FILES: ${{ steps.changedfiles.outputs.all_changed_files }}
         run: |
           for FILE in ${ALL_CHANGED_FILES}; do
-            echo "::warning file=$FILE,line=1::Vendored files should rarely change: https://github.com/pixiebrix/pixiebrix-extension/pull/7941"
+            echo "::warning file=$FILE,line=0::Vendored files should rarely change: https://github.com/pixiebrix/pixiebrix-extension/pull/7941"
           done
-          exit 1
+          exit 1 # Make the job fail for visibility https://github.com/pixiebrix/pixiebrix-extension/pull/7941#discussion_r1528517121
